CREATE DATABASE IF NOT EXISTS `user`;

CREATE TABLE user_profiles (
    id BIGINT PRIMARY KEY COMMENT 'ID',
    account VARCHAR(50) NOT NULL COMMENT '账户',
    password VARCHAR(100) NOT NULL COMMENT '密码',
    email VARCHAR(100) COMMENT '邮箱',
    phone_number VARCHAR(20) COMMENT '手机号码',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '用户基本信息表';

CREATE TABLE user_details (
  id BIGINT PRIMARY KEY COMMENT 'ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  avatar_filename VARCHAR(255) COMMENT '头像文件名',
  signature TEXT COMMENT '签名',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE
) COMMENT '用户详细信息表';