server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: 192.168.232.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        ip-address: ${spring.cloud.client.ip-address}
        heartbeat:
          enabled: true
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**