server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: consul-client-gateway
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        ip-address: ${spring.cloud.client.ip-address}
        heartbeat:
          enabled: true
        health-check-critical-timeout: 30s
    gateway:
      routes:
        - id: user
          uri: http://user-service:8081
          predicates:
            - Path=/user/**